version: 2
updates:
- package-ecosystem: bundler
  directory: "/danger"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
  target-branch: chore/dependency-update
  labels:
  - automerge
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
  target-branch: chore/dependency-update
  labels:
  - automerge
