name: Build

on:
  push:
    branches:
      - master
      - chore/dependency-update
      - feature/github-action
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install dependencies
        run: ./gradlew dependencies --stacktrace --scan
      - name: Quality checks
        run: ./gradlew lint --stacktrace --scan
      - name: Assemble Release
        run: ./gradlew clean assembleRelease --stacktrace --scan

      - uses: actions/upload-artifact@v2
        with:
          name: outputs
          path: app/build/outputs