name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Assemble Release
        run: ./gradlew clean assembleRelease

      - name: Archive release APK
        run: cp app/build/outputs/apk/release/*.apk release.apk

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: appdistribution:distribute release.apk  \
            --app ${{ secrets.FIREBASE_APP_ID }}  \
            --release-notes "Bug fixes and improvements"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}